# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 14:27
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('domanda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='danno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foglio', models.CharField(default='', max_length=50, verbose_name='Fogli colpiti da danno')),
                ('particella', models.CharField(default='', max_length=50)),
                ('coltura', models.CharField(default='', max_length=50)),
                ('varieta', models.CharField(blank=True, max_length=50, verbose_name='variet\xe0 colturale')),
                ('SumTot', models.FloatField(default=0, verbose_name='Superficie totale particelle ettari')),
                ('SumSem', models.FloatField(default=0, verbose_name='Superficie seminativa particella ettari')),
                ('PercDanno', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% stimata del danno')),
                ('Produzione', models.BigIntegerField(default=0, verbose_name='produzione prevista nella particella')),
                ('PerProdPersa', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% produzione persa')),
                ('ValoreDanno', models.BigIntegerField(default=0, verbose_name='ipotetico valore del danno stimato dal dichiarante')),
                ('NumPianteDan', models.BigIntegerField(blank=True, default=0, verbose_name='numero piante danneggiate')),
                ('TipoPiante', models.CharField(blank=True, max_length=50)),
                ('SelvagginaSem', models.CharField(default='', max_length=250, verbose_name='Selvaggina che ha fatto i danni alla coltura')),
                ('OpereProtezione', models.CharField(blank=True, max_length=250)),
                ('data_ins', models.DateField(auto_now_add=True, verbose_name='Data inserimento')),
                ('stato_pratica', models.CharField(choices=[('lavorazione', 'In lavorazione'), ('rilievo', 'In rilievo'), ('completa', 'Completa')], default='lavorazione', max_length=20)),
                ('fog_part_certified', models.ManyToManyField(help_text='aiuto', to='domanda.CatastaleSmall', verbose_name='Foglio Particella da Catastale')),
                ('richiedente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'danno',
                'verbose_name_plural': 'danni',
            },
        ),
    ]
