# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-09 14:37
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domanda', '0005_danno_rilevatore'),
    ]

    operations = [
        migrations.CreateModel(
            name='catastale_new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(max_length=5)),
                ('sub', models.CharField(max_length=3)),
                ('foglio', models.CharField(max_length=8)),
                ('idseq', models.BigIntegerField()),
                ('codfoglio', models.CharField(max_length=10)),
                ('fe466001', models.CharField(max_length=50)),
                ('comune', models.CharField(max_length=250)),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name': 'catastale1',
                'verbose_name_plural': 'catastali1',
            },
        ),
        migrations.AlterField(
            model_name='danno',
            name='CAA',
            field=models.ForeignKey(blank=True, help_text='Centro di Assistenza agricolo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
