# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-09 15:39
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domanda', '0006_auto_20180209_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='quadranti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.FloatField()),
                ('left', models.FloatField()),
                ('top', models.FloatField()),
                ('right', models.FloatField()),
                ('bottom', models.FloatField()),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=3003)),
            ],
        ),
    ]
