# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-15 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domanda', '0007_quadranti'),
    ]

    operations = [
        migrations.AddField(
            model_name='catastalesmall',
            name='comune',
            field=models.CharField(default='', max_length=250),
        ),
    ]
