# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-15 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domanda', '0008_catastalesmall_comune'),
    ]

    operations = [
        migrations.DeleteModel(
            name='catastale_new',
        ),
    ]
